# Generated by Django 4.0.6 on 2022-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
